# Generated by Django 5.2 on 2026-05-01 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=50, verbose_name='Tabla')),
                ('registro_id', models.IntegerField(verbose_name='ID del registro')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar')], max_length=20, verbose_name='Accion')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuario')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores nuevos')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-fecha'],
            },
        ),
    ]
