# Generated by Django 5.2 on 2026-05-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('nombre_razon_social', models.CharField(max_length=100, verbose_name='Nombre / Razon Social')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DNI / CUIT')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes/', verbose_name='Foto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_razon_social'],
                'indexes': [models.Index(fields=['documento'], name='clientes_cl_documen_76f212_idx'), models.Index(fields=['nombre_razon_social'], name='clientes_cl_nombre__992b1e_idx')],
            },
        ),
    ]
