# Generated by Django 5.2 on 2026-10-04 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de debito'), ('TARJETA_CREDITO', 'Tarjeta de credito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CHEQUE', 'Cheque'), ('MERCADO_PAGO', 'Mercado Pago')], default='EFECTIVO', max_length=30, verbose_name='Metodo de pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia / Comprobante')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='N° Factura')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='IVA %')),
                ('iva_monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA monto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado de pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
