# Generated by Django 5.2 on 2026-10-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturas.factura', verbose_name='Factura'),
        ),
    ]
