# Generated by Django 5.2 on 2026-05-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ordenes.ordentrabajo', verbose_name='Orden de trabajo'),
        ),
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='neumatico', serialize=False, to='inventario.productobase')),
                ('marca_neumatico', models.CharField(max_length=50, verbose_name='Marca del neumatico')),
                ('modelo_neumatico', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('ancho', models.PositiveIntegerField(verbose_name='Ancho (mm)')),
                ('perfil', models.PositiveIntegerField(verbose_name='Perfil (%)')),
                ('diametro', models.PositiveIntegerField(verbose_name='Diametro (R)')),
                ('indice_carga', models.CharField(blank=True, max_length=10, verbose_name='Indice de carga')),
                ('indice_velocidad', models.CharField(blank=True, max_length=5, verbose_name='Indice de velocidad')),
                ('tipo', models.CharField(choices=[('VERANO', 'Verano'), ('INVIERNO', 'Invierno'), ('ALL_SEASON', 'All Season'), ('OFF_ROAD', 'Off Road')], default='ALL_SEASON', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], default='NUEVO', max_length=10, verbose_name='Estado')),
                ('profundidad_restante', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Profundidad restante (mm)')),
            ],
            options={
                'verbose_name': 'Neumatico',
                'verbose_name_plural': 'Neumaticos',
            },
        ),
        migrations.CreateModel(
            name='RepuestoGenerico',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='repuesto', serialize=False, to='inventario.productobase')),
                ('marca_repuesto', models.CharField(blank=True, max_length=50, verbose_name='Marca del repuesto')),
                ('numero_parte', models.CharField(blank=True, max_length=100, verbose_name='Numero de parte')),
                ('compatible_con', models.TextField(blank=True, verbose_name='Compatible con (marca/modelo/anio)')),
            ],
            options={
                'verbose_name': 'Repuesto Generico',
                'verbose_name_plural': 'Repuestos Genericos',
            },
        ),
        migrations.AddField(
            model_name='productobase',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='inventario.categoriaproducto', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.productobase', verbose_name='Producto'),
        ),
        migrations.AddIndex(
            model_name='productobase',
            index=models.Index(fields=['codigo_sku'], name='inventario__codigo__cd5f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='productobase',
            index=models.Index(fields=['tipo_producto'], name='inventario__tipo_pr_2475f9_idx'),
        ),
    ]
