# Generated by Django 5.2 on 2026-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='tipo',
            field=models.CharField(choices=[('REPUESTO', 'Repuesto'), ('NEUMATICO', 'Neumático')], default='REPUESTO', max_length=20, verbose_name='Tipo de categoría'),
        ),
    ]
