# Generated by Django 5.2 on 2026-10-04 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Anio')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN / Nro. Chasis')),
                ('color', models.CharField(choices=[('BLANCO', 'Blanco'), ('NEGRO', 'Negro'), ('GRIS', 'Gris'), ('PLATA', 'Plata'), ('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('NARANJA', 'Naranja'), ('MARRON', 'Marron'), ('OTRO', 'Otro')], default='BLANCO', max_length=20, verbose_name='Color')),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, verbose_name='Kilometraje actual')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['placa'], name='vehiculos_v_placa_4999e1_idx'), models.Index(fields=['cliente'], name='vehiculos_v_cliente_88ee59_idx')],
            },
        ),
    ]
