# Generated by Django 5.2 on 2026-10-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Anio'),
        ),
    ]
