# Generated by Django 5.2 on 2026-05-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo en km')),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo en meses')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('ATENDIDA', 'Atendida'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('km_estimado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km estimado para servicio')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantenimiento', to='vehiculos.vehiculo', verbose_name='Vehiculo')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mantenimiento.tiposervicio', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
